pipeline{
   agent any 
   stages{
        stage('Build'){
             steps {
              echo "Building ....."
              buildApp()
           }
         }
        stage('Test'){
           steps {
              echo "Testing....."
           } 
         }
        stage('Deploy'){
           steps {
              echo "Deploying...."
              deployEnvironment('dev')
          }
        }
     }

}


def buildApp(){
  dir('declarative_pipeline'){
    def image = docker.build("hands-on-jenkins/myapp:${BUILD_NUMBER}")
  }
}

def deployEnvironment(environment){
     
     def containerName = ''
     def port = ''

     if(${environment} == 'dev'){
         containerName = 'app_dev'
         def port = '8888'
      } else {
        echo  'Wrong environment ....'
        System.exit()
     }

     sh "docker ps -f name=${containerName} -q | xargs --no-run-if-empty docker stop"
	  sh "docker ps -a -f name=${containerName} -q | xargs -r docker rm"
     sh  'docker run --name ${containerName} -p ${port}:5000 hands-on-jenkins/myapp:${BUILD_NUMBER}'

}
